/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ddev.TindaKart;

import components.ImageScaler;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.UIManager;

/**
 *
 * @author W10
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    sales sales = new sales();
    inventory inventory = new inventory();
    report report = new report();
    debt debt = new debt();
    ImageScaler scaler = new ImageScaler();

    public home() {
        this.setUndecorated(true);
        initComponents();
        URL imageUrl1 = getClass().getResource("/icons/receipt.png");
        URL imageUrl2 = getClass().getResource("/icons/package-2d.png");
        URL imageUrl3 = getClass().getResource("/icons/chart-bard.png");
        URL imageUrl4 = getClass().getResource("/icons/file-textd.png");
        URL logo = getClass().getResource("/images/logo_tindakart.png");

        ImageIcon img = new ImageIcon(logo);
        scaler.scaleImage(jLabel8, imageUrl1);
        scaler.scaleImage(jLabel7, imageUrl2);
        scaler.scaleImage(jLabel6, imageUrl3);
        scaler.scaleImage(jLabel4, imageUrl4);

        jPanel6.add(sales, "sales");
        jPanel6.add(inventory, "inventory");
        jPanel6.add(report, "report");
        jPanel6.add(debt, "debt");
        CardLayout cardLayout = (CardLayout) jPanel6.getLayout();
        cardLayout.show(jPanel6, "sales");
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Maximize the JFrame
        this.setVisible(true); // Make the JFrame visible

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); // Get screen dimensions
        this.setSize(screenSize.width, screenSize.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        minimize_label = new javax.swing.JLabel();
        exit_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        roundedPanel4 = new components.RoundedPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roundedPanel5 = new components.RoundedPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roundedPanel6 = new components.RoundedPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roundedPanel7 = new components.RoundedPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(27, 40));
        jPanel4.setLayout(new java.awt.GridLayout());

        jPanel11.setBackground(new java.awt.Color(51, 54, 82));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tindakart");
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel11);

        jPanel5.setBackground(new java.awt.Color(51, 54, 82));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 28));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel5.setLayout(flowLayout1);

        minimize_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minimize_label.setForeground(new java.awt.Color(255, 255, 255));
        minimize_label.setText("_");
        minimize_label.setPreferredSize(new java.awt.Dimension(20, 20));
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });
        jPanel5.add(minimize_label);

        exit_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit_label.setForeground(new java.awt.Color(255, 255, 255));
        exit_label.setText("X");
        exit_label.setPreferredSize(new java.awt.Dimension(20, 20));
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
        });
        jPanel5.add(exit_label);

        jPanel4.add(jPanel5);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 504));

        roundedPanel4.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel4.setOpaque(false);
        roundedPanel4.setPreferredSize(new java.awt.Dimension(100, 28));
        roundedPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel4MouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(23, 23, 23));
        jLabel9.setText("Debt Tracking");

        jLabel4.setPreferredSize(new java.awt.Dimension(15, 17));

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9))
        );

        roundedPanel5.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel5.setOpaque(false);
        roundedPanel5.setPreferredSize(new java.awt.Dimension(100, 28));
        roundedPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel5MouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(23, 23, 23));
        jLabel10.setText("Report");

        jLabel6.setPreferredSize(new java.awt.Dimension(15, 17));

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(9, 9, 9))
        );

        roundedPanel6.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel6.setOpaque(false);
        roundedPanel6.setPreferredSize(new java.awt.Dimension(100, 28));
        roundedPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel6MouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(23, 23, 23));
        jLabel11.setText("Inventory");

        jLabel7.setPreferredSize(new java.awt.Dimension(15, 17));

        javax.swing.GroupLayout roundedPanel6Layout = new javax.swing.GroupLayout(roundedPanel6);
        roundedPanel6.setLayout(roundedPanel6Layout);
        roundedPanel6Layout.setHorizontalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        roundedPanel6Layout.setVerticalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9))
        );

        roundedPanel7.setBackground(new java.awt.Color(51, 54, 82));
        roundedPanel7.setOpaque(false);
        roundedPanel7.setPreferredSize(new java.awt.Dimension(100, 28));
        roundedPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel7MouseClicked(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sales");

        jLabel8.setPreferredSize(new java.awt.Dimension(15, 17));

        javax.swing.GroupLayout roundedPanel7Layout = new javax.swing.GroupLayout(roundedPanel7);
        roundedPanel7.setLayout(roundedPanel7Layout);
        roundedPanel7Layout.setHorizontalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        roundedPanel7Layout.setVerticalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(158, 158, 158));
        jLabel1.setText("GENERAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundedPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.CardLayout());
        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void roundedPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel4MouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) jPanel6.getLayout();
        cardLayout.show(jPanel6, "debt");

        jLabel9.setForeground(Color.WHITE);
        jLabel10.setForeground(new Color(0x171717));
        jLabel11.setForeground(new Color(0x171717));
        jLabel12.setForeground(new Color(0x171717));

        roundedPanel4.setBackground(new Color(51, 54, 82));
        roundedPanel6.setBackground(Color.WHITE);
        roundedPanel5.setBackground(Color.WHITE);
        roundedPanel7.setBackground(Color.WHITE);
        
        URL imageUrl1 = getClass().getResource("/icons/receiptd.png");
        URL imageUrl2 = getClass().getResource("/icons/package-2d.png");
        URL imageUrl3 = getClass().getResource("/icons/chart-bard.png");
        URL imageUrl4 = getClass().getResource("/icons/file-text.png");
        scaler.scaleImage(jLabel8, imageUrl1);
        scaler.scaleImage(jLabel7, imageUrl2);
        scaler.scaleImage(jLabel6, imageUrl3);
        scaler.scaleImage(jLabel4, imageUrl4);
    }//GEN-LAST:event_roundedPanel4MouseClicked

    private void roundedPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel5MouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) jPanel6.getLayout();
        cardLayout.show(jPanel6, "report");
        jLabel10.setForeground(Color.WHITE);
        jLabel11.setForeground(new Color(0x171717));
        jLabel9.setForeground(new Color(0x171717));
        jLabel12.setForeground(new Color(0x171717));

        roundedPanel5.setBackground(new Color(51, 54, 82));
        roundedPanel6.setBackground(Color.WHITE);
        roundedPanel7.setBackground(Color.WHITE);
        roundedPanel4.setBackground(Color.WHITE);
        
        URL imageUrl1 = getClass().getResource("/icons/receiptd.png");
        URL imageUrl2 = getClass().getResource("/icons/package-2d.png");
        URL imageUrl3 = getClass().getResource("/icons/chart-bar.png");
        URL imageUrl4 = getClass().getResource("/icons/file-textd.png");
        scaler.scaleImage(jLabel8, imageUrl1);
        scaler.scaleImage(jLabel7, imageUrl2);
        scaler.scaleImage(jLabel6, imageUrl3);
        scaler.scaleImage(jLabel4, imageUrl4);
    }//GEN-LAST:event_roundedPanel5MouseClicked

    private void roundedPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel6MouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) jPanel6.getLayout();
        cardLayout.show(jPanel6, "inventory");
        jLabel11.setForeground(Color.WHITE);
        jLabel9.setForeground(new Color(0x171717));
        jLabel10.setForeground(new Color(0x171717));
        jLabel12.setForeground(new Color(0x171717));

        roundedPanel6.setBackground(new Color(51, 54, 82));
        roundedPanel7.setBackground(Color.WHITE);
        roundedPanel5.setBackground(Color.WHITE);
        roundedPanel4.setBackground(Color.WHITE);
        
        URL imageUrl1 = getClass().getResource("/icons/receiptd.png");
        URL imageUrl2 = getClass().getResource("/icons/package-2.png");
        URL imageUrl3 = getClass().getResource("/icons/chart-bard.png");
        URL imageUrl4 = getClass().getResource("/icons/file-textd.png");
        scaler.scaleImage(jLabel8, imageUrl1);
        scaler.scaleImage(jLabel7, imageUrl2);
        scaler.scaleImage(jLabel6, imageUrl3);
        scaler.scaleImage(jLabel4, imageUrl4);
    }//GEN-LAST:event_roundedPanel6MouseClicked

    private void roundedPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel7MouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) jPanel6.getLayout();
        cardLayout.show(jPanel6, "sales");
        jLabel12.setForeground(Color.WHITE);
        jLabel10.setForeground(new Color(0x171717));
        jLabel11.setForeground(new Color(0x171717));
        jLabel9.setForeground(new Color(0x171717));

        roundedPanel7.setBackground(new Color(51, 54, 82));
        roundedPanel6.setBackground(Color.WHITE);
        roundedPanel5.setBackground(Color.WHITE);
        roundedPanel4.setBackground(Color.WHITE);

        URL imageUrl1 = getClass().getResource("/icons/receipt.png");
        URL imageUrl2 = getClass().getResource("/icons/package-2d.png");
        URL imageUrl3 = getClass().getResource("/icons/chart-bard.png");
        URL imageUrl4 = getClass().getResource("/icons/file-textd.png");
        scaler.scaleImage(jLabel8, imageUrl1);
        scaler.scaleImage(jLabel7, imageUrl2);
        scaler.scaleImage(jLabel6, imageUrl3);
        scaler.scaleImage(jLabel4, imageUrl4);


    }//GEN-LAST:event_roundedPanel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel minimize_label;
    private components.RoundedPanel roundedPanel4;
    private components.RoundedPanel roundedPanel5;
    private components.RoundedPanel roundedPanel6;
    private components.RoundedPanel roundedPanel7;
    // End of variables declaration//GEN-END:variables

}
