/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ddev.TindaKart;

import components.ImageScaler;
import java.awt.Color;
import java.awt.Component;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author W10
 */
public class inventory extends javax.swing.JPanel {

    /**
     * Creates new form inventory
     */
        ImageScaler scaler = new ImageScaler();

    public inventory() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{}, // Initial empty rows
                new String[]{"ID", "Name", "Quantity", "Price", "Status"} // Column names
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Make only the Quantity column editable (index 2)
                return column == 2;
            }
        };
        jTable1.setModel(model);
        URL imageUrl1 = getClass().getResource("/icons/package-2d.png");
        scaler.scaleImage(jLabel8, imageUrl1);
        populateInventoryTable();
        
                model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    int row = e.getFirstRow();
                    int column = e.getColumn();

                    // Check if the Quantity column was edited
                    if (column == 2) {
                        updateQuantityAndStatus(row);
                    }
                }
            }
        });
    }
    
    private void updateQuantityAndStatus(int row) {
        try {
            // Get the ID and new quantity from the table
            int id = (int) jTable1.getValueAt(row, 0); // ID column
            int newQuantity = Integer.parseInt(jTable1.getValueAt(row, 2).toString()); // Quantity column

            String newStatus = newQuantity > 0 ? "In Stock" : "Out of Stock";

            // Update the table with the new status
            jTable1.setValueAt(newStatus, row, 4); // Status column

            // Update the database
            try (Connection conn = DatabaseConnection.getConnection()) {
                String sql = "UPDATE inventory SET quantity = ?, status = ? WHERE id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, newQuantity);
                pstmt.setString(2, newStatus);
                pstmt.setInt(3, id);
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Inventory updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error updating inventory in the database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity.", "Error", JOptionPane.ERROR_MESSAGE);
            // Revert the quantity in the table to the previous value
            populateInventoryTable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        roundedPanelBorderless3 = new components.RoundedPanelBorderless();
        nameField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roundedPanelBorderless2 = new components.RoundedPanelBorderless();
        quantityField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        roundedPanelBorderless4 = new components.RoundedPanelBorderless();
        priceField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        myButtonborderless5 = new components.MyButtonborderless();
        myButtonborderless3 = new components.MyButtonborderless();
        myButtonborderless4 = new components.MyButtonborderless();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 126));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Inventory Management");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setOpaque(false);

        jLabel3.setText("Product Name");

        roundedPanelBorderless3.setBackground(new java.awt.Color(255, 255, 255));

        nameField.setToolTipText("Quantity");
        nameField.setBorder(null);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanelBorderless3Layout = new javax.swing.GroupLayout(roundedPanelBorderless3);
        roundedPanelBorderless3.setLayout(roundedPanelBorderless3Layout);
        roundedPanelBorderless3Layout.setHorizontalGroup(
            roundedPanelBorderless3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelBorderless3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameField)
                .addContainerGap())
        );
        roundedPanelBorderless3Layout.setVerticalGroup(
            roundedPanelBorderless3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelBorderless3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addComponent(roundedPanelBorderless3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(roundedPanelBorderless3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);

        jLabel2.setText("Quantity");

        roundedPanelBorderless2.setBackground(new java.awt.Color(255, 255, 255));

        quantityField.setToolTipText("Quantity");
        quantityField.setBorder(null);
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanelBorderless2Layout = new javax.swing.GroupLayout(roundedPanelBorderless2);
        roundedPanelBorderless2.setLayout(roundedPanelBorderless2Layout);
        roundedPanelBorderless2Layout.setHorizontalGroup(
            roundedPanelBorderless2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelBorderless2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quantityField)
                .addContainerGap())
        );
        roundedPanelBorderless2Layout.setVerticalGroup(
            roundedPanelBorderless2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelBorderless2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addComponent(roundedPanelBorderless2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(roundedPanelBorderless2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setOpaque(false);

        jLabel4.setText("Price");

        roundedPanelBorderless4.setBackground(new java.awt.Color(255, 255, 255));

        priceField.setToolTipText("Quantity");
        priceField.setBorder(null);
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanelBorderless4Layout = new javax.swing.GroupLayout(roundedPanelBorderless4);
        roundedPanelBorderless4.setLayout(roundedPanelBorderless4Layout);
        roundedPanelBorderless4Layout.setHorizontalGroup(
            roundedPanelBorderless4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelBorderless4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceField)
                .addContainerGap())
        );
        roundedPanelBorderless4Layout.setVerticalGroup(
            roundedPanelBorderless4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelBorderless4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 211, Short.MAX_VALUE))
                    .addComponent(roundedPanelBorderless4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(roundedPanelBorderless4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel8);

        jLabel8.setPreferredSize(new java.awt.Dimension(25, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        myButtonborderless5.setForeground(new java.awt.Color(255, 255, 255));
        myButtonborderless5.setText("Add Product");
        myButtonborderless5.setPreferredSize(new java.awt.Dimension(150, 30));
        myButtonborderless5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButtonborderless5ActionPerformed(evt);
            }
        });
        jPanel5.add(myButtonborderless5);

        myButtonborderless3.setForeground(new java.awt.Color(255, 255, 255));
        myButtonborderless3.setText("Refresh");
        myButtonborderless3.setPreferredSize(new java.awt.Dimension(150, 30));
        myButtonborderless3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButtonborderless3ActionPerformed(evt);
            }
        });
        jPanel5.add(myButtonborderless3);

        myButtonborderless4.setBackground(new java.awt.Color(255, 51, 51));
        myButtonborderless4.setForeground(new java.awt.Color(255, 255, 255));
        myButtonborderless4.setText("Delete Product");
        myButtonborderless4.setDestructive(true);
        myButtonborderless4.setPreferredSize(new java.awt.Dimension(150, 30));
        myButtonborderless4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButtonborderless4ActionPerformed(evt);
            }
        });
        jPanel5.add(myButtonborderless4);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void myButtonborderless4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButtonborderless4ActionPerformed
        // TODO add your handling code here:
        deleteInventoryItem();
    }//GEN-LAST:event_myButtonborderless4ActionPerformed

    private void myButtonborderless3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButtonborderless3ActionPerformed
        // TODO add your handling code here:
         populateInventoryTable();
    }//GEN-LAST:event_myButtonborderless3ActionPerformed

    private void myButtonborderless5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButtonborderless5ActionPerformed
        // TODO add your handling code here:
                saveToDatabase();
    }//GEN-LAST:event_myButtonborderless5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private components.MyButtonborderless myButtonborderless3;
    private components.MyButtonborderless myButtonborderless4;
    private components.MyButtonborderless myButtonborderless5;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField quantityField;
    private components.RoundedPanelBorderless roundedPanelBorderless2;
    private components.RoundedPanelBorderless roundedPanelBorderless3;
    private components.RoundedPanelBorderless roundedPanelBorderless4;
    // End of variables declaration//GEN-END:variables
   private void saveToDatabase() {
        String name = nameField.getText();
        String priceStr = priceField.getText();
        String quantityStr = quantityField.getText();

        if (name.isEmpty() || priceStr.isEmpty() || quantityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double price = Double.parseDouble(priceStr);
            int quantity = Integer.parseInt(quantityStr);

            if (price <= 0 || quantity < 0) {
                JOptionPane.showMessageDialog(this, "Price must be greater than 0 and quantity cannot be negative!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try (Connection conn = DatabaseConnection.getConnection()) {
                String sql = "INSERT INTO inventory (name, quantity, price, status) VALUES (?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, name);
                pstmt.setInt(2, quantity);
                pstmt.setDouble(3, price);
                pstmt.setString(4, "In Stock"); // Default status "available"
                pstmt.executeUpdate();

                // Update display area and reset text fields
//            displayArea.append("Saved: " + name + ", Price: " + price + ", Quantity: " + quantity + "\n");
                nameField.setText("");
                priceField.setText("");
                quantityField.setText("");

                // Refresh the table with updated data
                populateInventoryTable();

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error saving to database!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for price and quantity!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void populateInventoryTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "SELECT id, name, quantity, price, status FROM inventory";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            // Populate the table with the fetched data
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                int quantity = rs.getInt("quantity");
                double price = rs.getDouble("price");
                String status = rs.getString("status");

                model.addRow(new Object[]{id, name, quantity, price, status});
            }

            // Set the custom cell renderer for the status column
            jTable1.getColumnModel().getColumn(4).setCellRenderer(new StatusColumnCellRenderer());

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading inventory data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private class StatusColumnCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            String status = (String) value;
            label.setOpaque(true);
            label.setHorizontalAlignment(JLabel.CENTER);
            
            if ("In Stock".equalsIgnoreCase(status)) {
                label.setBackground(new Color(0, 150, 0)); // Green
                label.setForeground(Color.WHITE);
                label.setText("In Stock");
            } else if ("Out of Stock".equalsIgnoreCase(status)) {
                label.setBackground(new Color(150, 0, 0)); // Red
                label.setForeground(Color.WHITE);
                label.setText("Out of Stock");
            } else {
                label.setBackground(table.getBackground());
                label.setForeground(table.getForeground());
            }
            
            return label;
        }
    }

    private void deleteInventoryItem() {
        // Get the selected row index
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an inventory item to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the inventory ID from the selected row
        int inventoryId = (int) jTable1.getValueAt(selectedRow, 0); // Assuming ID is in the first column

        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this item?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DatabaseConnection.getConnection()) {
                String sql = "DELETE FROM inventory WHERE id = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, inventoryId);
                pstmt.executeUpdate();

                // Refresh the table after deletion
                populateInventoryTable();
                JOptionPane.showMessageDialog(this, "Inventory item deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error deleting inventory item!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

}
