import { ArrowRight, LockKeyhole, Store } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { authApi, type CurrentUser } from '../api'
import { Badge } from '../components/ui/badge'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardHeader } from '../components/ui/card'
import { Input } from '../components/ui/input'

export function LoginPage({ onLogin, onBack, onRegister }: { onLogin: (user: CurrentUser) => void; onBack: () => void; onRegister: () => void }) {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  async function submit(event: FormEvent) {
    event.preventDefault(); setSubmitting(true); setError('')
    try { onLogin(await authApi.login(username, password)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.') } finally { setSubmitting(false) }
  }
  return <main className="grid min-h-screen place-items-center bg-slate-950 px-4 py-8"><div className="grid w-full max-w-5xl overflow-hidden rounded-[2rem] bg-white shadow-2xl shadow-indigo-950/20 lg:grid-cols-[.9fr_1.1fr]"><section className="hidden bg-gradient-to-br from-indigo-600 via-indigo-700 to-slate-950 p-10 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="mb-16 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white/15 font-black">TK</span><span className="font-bold">TindaKart</span></div><Badge className="border-white/20 bg-white/10 text-indigo-100">Store operations</Badge><h1 className="mt-5 max-w-sm text-5xl font-black tracking-[-.06em]">Your store, in control.</h1><p className="mt-5 max-w-sm text-sm leading-7 text-indigo-100">A focused POS workspace for everyday selling, inventory, and store growth.</p></div><p className="text-xs text-indigo-200">Secure session · Vendor-scoped access · PWA ready</p></section><section className="p-6 sm:p-10"><button type="button" onClick={onBack} className="mb-12 text-sm font-semibold text-slate-500 hover:text-slate-950">← Back to TindaKart</button><Card className="border-0 shadow-none"><CardHeader className="px-0"><div className="mb-3 grid size-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><LockKeyhole size={20} /></div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Welcome back</p><h2 className="text-3xl font-black tracking-[-.04em] text-slate-950">Sign in to your store</h2><p className="text-sm text-slate-500">Continue to your TindaKart workspace.</p></CardHeader><CardContent className="px-0"><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold text-slate-700">Username<Input value={username} onChange={event => setUsername(event.target.value)} autoComplete="username" required /></label><label className="block text-sm font-semibold text-slate-700">Password<Input type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" required /></label>{error && <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<Button type="submit" size="lg" disabled={submitting}>{submitting ? 'Signing in…' : <>Sign in <ArrowRight size={17} /></>}</Button></form><div className="mt-8 border-t border-slate-100 pt-6 text-center text-sm text-slate-500">New to TindaKart? <button type="button" onClick={onRegister} className="font-bold text-indigo-600 hover:text-indigo-500">Create a free owner account</button></div></CardContent></Card></section></div></main>
}

export function RegistrationPage({ onBack, onRegistered }: { onBack: () => void; onRegistered: () => void }) {
  const [form, setForm] = useState({ username: '', password: '', displayName: '', vendorName: '', storeName: '', storeCode: '' })
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setSubmitting(true); setError(''); try { await authApi.registerVendor(form); onRegistered() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create account.') } finally { setSubmitting(false) } }
  return <main className="grid min-h-screen place-items-center bg-slate-100 px-4 py-8"><Card className="w-full max-w-2xl"><CardHeader><button type="button" onClick={onBack} className="mb-6 w-fit text-sm font-semibold text-slate-500 hover:text-slate-950">← Back</button><Badge className="w-fit">Free owner plan</Badge><h1 className="mt-3 text-3xl font-black tracking-[-.04em]">Create your store account</h1><p className="text-sm text-slate-500">Start with POS and catalog access. Add staff seats or features later as your store grows.</p></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Your name<Input value={form.displayName} onChange={event => setForm({ ...form, displayName: event.target.value })} required /></label><label className="text-sm font-semibold text-slate-700">Username<Input value={form.username} onChange={event => setForm({ ...form, username: event.target.value })} required /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Password<Input type="password" minLength={8} value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} required /></label><label className="text-sm font-semibold text-slate-700">Business name<Input value={form.vendorName} onChange={event => setForm({ ...form, vendorName: event.target.value })} required /></label><label className="text-sm font-semibold text-slate-700">First store name<Input value={form.storeName} onChange={event => setForm({ ...form, storeName: event.target.value })} required /></label><label className="text-sm font-semibold text-slate-700">Store code<Input value={form.storeCode} onChange={event => setForm({ ...form, storeCode: event.target.value })} required /></label>{error && <p className="sm:col-span-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<Button className="sm:col-span-2" type="submit" size="lg" disabled={submitting}>{submitting ? 'Creating account…' : <><Store size={17} /> Create free account</>}</Button></form></CardContent></Card></main>
}
