import { useEffect, useState } from 'react'
import { deliveryApi, type Delivery } from './api'

export function DeliveryReceiving({ vendorId, storeId }: { vendorId: number; storeId: number }) {
  const [deliveries, setDeliveries] = useState<Delivery[]>([]); const [selected, setSelected] = useState<Delivery | null>(null); const [values, setValues] = useState<Record<number, { received: string; missing: string; damaged: string }>>({}); const [message, setMessage] = useState('')
  const reload = () => deliveryApi.list(vendorId, storeId).then(items => { setDeliveries(items); if (selected) setSelected(items.find(item => item.id === selected.id) ?? null) }).catch(error => setMessage(error.message))
  useEffect(() => { void reload() }, [vendorId, storeId])
  function choose(delivery: Delivery) { setSelected(delivery); setValues(Object.fromEntries(delivery.items.map(item => [item.id, { received: String(item.quantityOrdered), missing: '0', damaged: '0' }]))) }
  async function receive() { if (!selected) return; try { await deliveryApi.receiveDetails(vendorId, storeId, selected.id, selected.items.map(item => ({ deliveryItemId: item.id, received: Number(values[item.id]?.received ?? 0), missing: Number(values[item.id]?.missing ?? 0), damaged: Number(values[item.id]?.damaged ?? 0) }))); setMessage('Delivery quantities recorded and stock updated.'); setSelected(null); reload() } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to record delivery quantities.') } }
  const pending = deliveries.filter(item => item.status === 'UPCOMING' || item.status === 'IN_TRANSIT')
  return <div className="receiving-panel"><div className="section-heading"><h3>Receive with variance</h3><span className="muted">Received stock is added to inventory; missing/damaged stock is not.</span></div>{message && <p className="form-message">{message}</p>}{pending.length ? <div className="store-list">{pending.map(delivery => <button className="store-row receiving-row" key={delivery.id} onClick={() => choose(delivery)}><span>#{delivery.id} · {delivery.supplierName}</span><span>{delivery.status} · {delivery.expectedDate}</span></button>)}</div> : <p className="empty-state">No pending deliveries.</p>}{selected && <div className="compact-form"><h4>Delivery #{selected.id} quantities</h4>{selected.items.map(item => <div className="receiving-item" key={item.id}><strong>{item.productName}</strong><small>Ordered: {item.quantityOrdered}</small><input type="number" min="0" max={Number(item.quantityOrdered)} step="0.001" placeholder="Received" value={values[item.id]?.received ?? ''} onChange={e => setValues({ ...values, [item.id]: { ...values[item.id], received: e.target.value } })} /><input type="number" min="0" max={Number(item.quantityOrdered)} step="0.001" placeholder="Missing" value={values[item.id]?.missing ?? ''} onChange={e => setValues({ ...values, [item.id]: { ...values[item.id], missing: e.target.value } })} /><input type="number" min="0" max={Number(item.quantityOrdered)} step="0.001" placeholder="Damaged" value={values[item.id]?.damaged ?? ''} onChange={e => setValues({ ...values, [item.id]: { ...values[item.id], damaged: e.target.value } })} /></div>)}<div><button className="primary-button compact" onClick={receive}>Record quantities</button><button className="secondary-button compact" onClick={() => setSelected(null)}>Cancel</button></div></div>}</div>
}
