spring.flyway.enabled=true
spring.sql.init.mode=never
tindakart.bootstrap.admin-username=
tindakart.bootstrap.admin-password=
logging.level.com.ddev.tindakart=WARN
logging.level.org.springframework.security=ERROR
