import { useEffect, useState } from 'react'
import { CreditCard, ExternalLink } from 'lucide-react'
import { billingApi, type Vendor } from '../../api'
import { AdminPageHeader } from '../../components/admin/AdminShell'
import { Card, CardContent } from '../../components/ui/card'

export function BillingActivityPage({ vendors }: { vendors: Vendor[] }) {
  const [selected, setSelected] = useState<Vendor | null>(vendors[0] ?? null)
  const [history, setHistory] = useState<{ id: number; checkoutUrl: string; amount: number; currency: string; status: string; createdAt: string }[]>([])
  const [loading, setLoading] = useState(false)
  useEffect(() => { if (!selected) return; setLoading(true); billingApi.history(selected.id).then(setHistory).catch(() => setHistory([])).finally(() => setLoading(false)) }, [selected])
  return <><AdminPageHeader eyebrow="Revenue operations" title="Billing activity" description="Review checkout sessions and payment status by vendor. Payment creation remains controlled by the vendor billing workflow." /><div className="mb-6 flex flex-wrap gap-2">{vendors.map(vendor => <button key={vendor.id} onClick={() => setSelected(vendor)} className={`rounded-xl px-4 py-2 text-sm font-bold ${selected?.id === vendor.id ? 'bg-slate-950 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{vendor.name}</button>)}</div><Card><CardContent className="p-0">{!selected ? <p className="p-8 text-sm text-slate-500">Create a vendor to view billing activity.</p> : loading ? <p className="p-8 text-sm text-slate-500">Loading billing activity…</p> : history.length === 0 ? <div className="grid place-items-center p-16 text-center"><CreditCard className="mb-3 text-slate-300" size={32} /><p className="text-sm text-slate-500">No checkout sessions for {selected.name}.</p></div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Session</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Created</th><th className="px-5 py-4" /></tr></thead><tbody>{history.map(item => <tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4 font-semibold">#{item.id}</td><td className="px-5 py-4">{item.currency} {item.amount.toLocaleString()}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{item.status}</span></td><td className="px-5 py-4 text-slate-500">{new Date(item.createdAt).toLocaleString()}</td><td className="px-5 py-4 text-right"><a className="inline-flex items-center gap-1 text-xs font-bold text-indigo-600" href={item.checkoutUrl} target="_blank" rel="noreferrer">Open <ExternalLink size={13} /></a></td></tr>)}</tbody></table></div>}</CardContent></Card></>
}
